project:
  type: website
  output-dir: docs

website:
  title: "Home"
  favicon: logo.png
  navbar:
    left:
      - href: about.qmd
        text: About
      - href: teaching/index.qmd
        text: Teaching
      - href: projects/index.qmd
        text: Advised Projects
      - href: blog/index.qmd
        text: Blog
    right:
      - href: files/Mandery_CV_2025.pdf
        text: CV

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor:
  render-on-save: true
