---
title: "The age of anxiety"
date: "2026-08-31"
---

It is an interesting time to be an educator. 
It has been noted that students are no longer bored in our classrooms, but anxious.

Anxious about being perceived by their peers. 
Anxious for what awaits them outside our institution's walls.
Anxious to be a part of a world that may not be the most kind to newcomers.

The anxiety surrounding transitional points in a person's life is a grounding human experience.
But it does seem like current transitional periods are more abrupt than in the past.

Why is this? Well, to most the answer to many things nowadays is technology. 
So it it our reliance on it? Or subservience to it? Something else?

One could argue that technology has made us ever connected. 
I am able to play video games with friends all over the world thanks to technology. 
I can spend time with those I care about even though we are miles apart.
But after I log off, there is an adjustment period of having to come back to my own reality.
So what it just an illusion of connection?

There is also something to be said about the renassaince of third spaces. 
I saw a couple hosting a linocut block party out of their garage to build up connection in their local community.
It did so well the first weekend, that they are hosting additional ones in the coming months (of which I'm really excited to attend!).

Is there a physicallity of connection and of sharing spaces with people that allows our brains to foster "true deep" connection.
What does it mean to feel connected? to others? to our community? to a larger... idk purpose?

Perhaps it's a balance of our senses. Some aspect of physicallity exists, but merely as a way to create a full experience.
And experience and connection can be two separate things. 




